name: store_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Icons
  cupertino_icons: ^1.0.2

  # State Management
  flutter_bloc: ^8.1.0
  equatable: ^2.0.5 
  
  # DI (Dependency Injection)
  get_it: ^7.6.0
  
  # Networking
  http: ^1.1.0
  
  # Code Generation Support
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Lints (стандартный линтер Flutter)
  flutter_lints: ^2.0.0

  # Code Generators (они должны быть тут!)
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true