name: string_search_app
description: A new Flutter project.

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  get_it: ^7.6.0
  injectable: ^2.3.0
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.5.2
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
