<<<<<<< HEAD
name: task_manager_clean_arch
description: Final Flutter project
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
=======
name: product_search_app
description: Simple Flutter app with BLoC, DI, Freezed and backend integration.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

>>>>>>> 5681d64 (Initial Flutter product search app)

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD

  dio: ^5.4.0
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
=======
  

  # UI icons (default, safe)
  cupertino_icons: ^1.0.8

  # State management (BLoC)
  flutter_bloc: ^8.1.6

  # Dependency Injection
  get_it: ^7.7.0

  # HTTP client (backend)
  dio: ^5.4.3

  # Freezed (data models)
>>>>>>> 5681d64 (Initial Flutter product search app)
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
<<<<<<< HEAD
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
=======
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
>>>>>>> 5681d64 (Initial Flutter product search app)

flutter:
  uses-material-design: true
