<<<<<<< HEAD
name: string_search_app
description: A new Flutter project.

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"
=======
name: navigation
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0
>>>>>>> 7e64f7aef3c19c2f6330f77de2b662882cb375e9

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD

  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  get_it: ^7.6.0
  injectable: ^2.3.0
  dio: ^5.4.0
=======
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
>>>>>>> 7e64f7aef3c19c2f6330f77de2b662882cb375e9

dev_dependencies:
  flutter_test:
    sdk: flutter
<<<<<<< HEAD
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.5.2
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
=======
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
>>>>>>> 7e64f7aef3c19c2f6330f77de2b662882cb375e9
