name: smart_searcher
description: A SmartSearcher app for notes with pattern search.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  
  # Dependency Injection
  get_it: ^7.2.0
  injectable: ^1.5.3
  
  # Networking
  dio: ^5.3.2
  retrofit: ^4.0.1
  logger: ^1.1.0
  
  # Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # UI
  flutter_slidable: ^2.0.0
  auto_route: ^7.8.1
  
  # Others
  equatable: ^2.0.5
  uuid: ^3.0.7
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  injectable_generator: ^1.5.3
  retrofit_generator: ^4.0.1
  auto_route_generator: ^7.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/